import pandas as pd
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00616/Tetuan%20City%20power%20consumption.csv")
df1 = df.select_dtypes(include=numerics)
df.head()
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nDemosntração do Banco de dados.\n')
print(df)
print('\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nDescrição do bando de dados com: Média, Desvio Padrão, Maior Valor, Menos Valor.\n')
print(df.describe())
print('\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nA médiana do banco de dados.\n')
print(df1.median())
print('\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nA moda do banco de dados.\n')
print(df1.mode())
print('\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nA aplicação do query.\n')
print(df.query('Temperature < 6'))
print(df.query('Humidity   > 80'))
print(df.query('Wind Speed > 1'))